class AvailabilityData{

  String dayText = '1';
  String weekText = 'Tue';
  String monthText = "Feb";
  bool icon1 = true;
  bool icon2 = true;
  bool icon3 = true;
  bool icon4 = true;

  List<Map<String, dynamic>> dateList = [
    {
      "monthText"   : "Jan",
      "dayText" : "1",
      "weekText" : "Sun",
      "icon1" : true,
      "icon2" : false,
      "icon3" : true,
      "icon4" : false,


    },
    {
      "monthText"   : "Jan",
      "dayText" : "2",
      "weekText" : "Mon",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "3",
      "weekText" : "Tue",
      "icon1" : false,
      "icon2" : true,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "4",
      "weekText" : "Wed",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "5",
      "weekText" : "Thu",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : true,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "6",
      "weekText" : "Fri",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "7",
      "weekText" : "Sat",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "8",
      "weekText" : "Son",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "9",
      "weekText" : "Mon",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "10",
      "weekText" : "Tue",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "11",
      "weekText" : "Wed",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "12",
      "weekText" : "Thu",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "13",
      "weekText" : "Fri",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "14",
      "weekText" : "Sat",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "15",
      "weekText" : "Sun",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "16",
      "weekText" : "Mon",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "17",
      "weekText" : "Tue",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "18",
      "weekText" : "Wed",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText" : "19",
      "weekText" : "Thu",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    },
    {
      "monthText"   : "Jan",
      "dayText": "20",
      "weekText": "Fri",
      "icon1" : false,
      "icon2" : false,
      "icon3" : false,
      "icon4" : false,
    }
  ];

  AvailabilityData();
}